[package]
name = "experiment"
version = "0.1.0"
authors = ["Michal Siedlaczek <michal.siedlaczek@nyu.edu>"]
edition = "2018"

[dependencies]
clap = "2.32"
tempdir = "0.3"
glob = "0.3"
os_pipe = "0.8"
